EVALUATE
SELECTCOLUMNS(
    SUMMARIZECOLUMNS(
        'BIOrcamentoConversao'[Número do Pedido],
        'BIOrcamentoConversao'[Data],
        'BIOrcamentoConversao'[Cliente],
        'BIOrcamentoConversao'[Cnpj],
        'BIOrcamentoConversao'[Tipo Cliente],
        'BIOrcamentoConversao'[Nome do Vendedor],
        'StatusWorkflow'[Descricao],

        FILTER(
            'dCalendario',
            'dCalendario'[Ano Atual] = "Ano Atual" &&
            'dCalendario'[Mês Atual] = "Mês Atual"
        ),
        FILTER(
            'BIOrcamentoConversao',
            'BIOrcamentoConversao'[oportunidade] = FALSE() &&
            'BIOrcamentoConversao'[Recompra] = FALSE()
        ),
        FILTER(
            'Licitacao',
            'Licitacao'[LIC] = "Não"
        ),

        "ETAPA 1 FUNIL Orçamentos Emitidos", MAX('BIOrcamentoConversao'[Orçamentos Totais]),
        "Valor", MAX('BIOrcamentoConversao'[Valor dos Orçamentos]),
        "ETAPA 2 FUNIL Orçamentos em Negociação", [e_OrcamentosNegociacao_Tabela],
        "ETAPA 3 FUNIL Aprovados pelo Cliente", [e_OrcamentosPedido_Tabela],
        "ETAPA 4 FUNIL Pedidos Faturados", [e_OrcamentosFaturado_Tabela],
        "Passou por Revisão Gestor", [e_OrcamentosNegociacao_RevisaoGestor_Tabela]
    ),
    "Núm. Orç.", [Número do Pedido],
    "Data de Criação", [Data],
    "Cliente", [Cliente],
    "CNPJ/ CPF", [Cnpj],
    "Tipo Cliente", [Tipo Cliente],
    "Vendedor", [Nome do Vendedor],
    "ETAPA 1 FUNIL Orçamentos Emitidos", [ETAPA 1 FUNIL Orçamentos Emitidos],
    "ETAPA 2 FUNIL Orçamentos em Negociação", [ETAPA 2 FUNIL Orçamentos em Negociação],
    "ETAPA 3 FUNIL Aprovados pelo Cliente", [ETAPA 3 FUNIL Aprovados pelo Cliente],
    "ETAPA 4 FUNIL Pedidos Faturados", [ETAPA 4 FUNIL Pedidos Faturados],
    "Passou por Revisão Gestor", [Passou por Revisão Gestor],
    "Valor", [Valor],
    "Status Atual", [Descricao]
)
